export const HttpStatusInfo: Record<string, IHttpStatusInfo> = {
    CONTINUE: { code: 100, response: 'Continue' },
    SWITCHING_PROTOCOLS: { code: 101, response: 'Switching Protocols' },
    PROCESSING: { code: 102, response: 'Processing' },
    OK: { code: 200, response: 'OK' },
    CREATED: { code: 201, response: 'Created' },
    ACCEPTED: { code: 202, response: 'Accepted' },
    NON_AUTHORITATIVE_INFORMATION: { code: 203, response: 'Non Authoritative Information' },
    NO_CONTENT: { code: 204, response: 'No Content' },
    RESET_CONTENT: { code: 205, response: 'Reset Content' },
    PARTIAL_CONTENT: { code: 206, response: 'Partial Content' },
    MULTI_STATUS: { code: 207, response: 'Multi-Status' },
    MULTIPLE_CHOICES: { code: 300, response: 'Multiple Choices' },
    MOVED_PERMANENTLY: { code: 301, response: 'Moved Permanently' },
    MOVED_TEMPORARILY: { code: 302, response: 'Moved Temporarily' },
    SEE_OTHER: { code: 303, response: 'See Other' },
    NOT_MODIFIED: { code: 304, response: 'Not Modified' },
    USE_PROXY: { code: 305, response: 'Use Proxy' },
    TEMPORARY_REDIRECT: { code: 307, response: 'Temporary Redirect' },
    PERMANENT_REDIRECT: { code: 308, response: 'Permanent Redirect' },
    BAD_REQUEST: { code: 400, response: 'Bad Request' },
    UNAUTHORIZED: { code: 401, response: 'Unauthorized' },
    PAYMENT_REQUIRED: { code: 402, response: 'Payment Required' },
    FORBIDDEN: { code: 403, response: 'Forbidden' },
    NOT_FOUND: { code: 404, response: 'Not Found' },
    METHOD_NOT_ALLOWED: { code: 405, response: 'Method Not Allowed' },
    NOT_ACCEPTABLE: { code: 406, response: 'Not Acceptable' },
    PROXY_AUTHENTICATION_REQUIRED: { code: 407, response: 'Proxy Authentication Required' },
    REQUEST_TIMEOUT: { code: 408, response: 'Request Timeout' },
    CONFLICT: { code: 409, response: 'Conflict' },
    GONE: { code: 410, response: 'Gone' },
    LENGTH_REQUIRED: { code: 411, response: 'Length Required' },
    PRECONDITION_FAILED: { code: 412, response: 'Precondition Failed' },
    REQUEST_TOO_LONG: { code: 413, response: 'Request Entity Too Large' },
    REQUEST_URI_TOO_LONG: { code: 414, response: 'Request-URI Too Long' },
    UNSUPPORTED_MEDIA_TYPE: { code: 415, response: 'Unsupported Media Type' },
    REQUESTED_RANGE_NOT_SATISFIABLE: { code: 416, response: 'Requested Range Not Satisfiable' },
    EXPECTATION_FAILED: { code: 417, response: 'Expectation Failed' },
    IM_A_TEAPOT: { code: 418, response: "I'm a teapot" },
    INSUFFICIENT_SPACE_ON_RESOURCE: { code: 419, response: 'Insufficient Space on Resource' },
    METHOD_FAILURE: { code: 420, response: 'Method Failure' },
    UNPROCESSABLE_ENTITY: { code: 422, response: 'Unprocessable Entity' },
    LOCKED: { code: 423, response: 'Locked' },
    FAILED_DEPENDENCY: { code: 424, response: 'Failed Dependency' },
    PRECONDITION_REQUIRED: { code: 428, response: 'Precondition Required' },
    TOO_MANY_REQUESTS: { code: 429, response: 'Too Many Requests' },
    REQUEST_HEADER_FIELDS_TOO_LARGE: { code: 431, response: 'Request Header Fields Too Large' },
    UNAVAILABLE_FOR_LEGAL_REASONS: { code: 451, response: 'Unavailable For Legal Reasons' },
    INTERNAL_SERVER_ERROR: { code: 500, response: 'Internal Server Error' },
    NOT_IMPLEMENTED: { code: 501, response: 'Not Implemented' },
    BAD_GATEWAY: { code: 502, response: 'Bad Gateway' },
    SERVICE_UNAVAILABLE: { code: 503, response: 'Service Unavailable' },
    GATEWAY_TIMEOUT: { code: 504, response: 'Gateway Timeout' },
    HTTP_VERSION_NOT_SUPPORTED: { code: 505, response: 'HTTP Version Not Supported' },
    INSUFFICIENT_STORAGE: { code: 507, response: 'Insufficient Storage' },
    NETWORK_AUTHENTICATION_REQUIRED: { code: 511, response: 'Network Authentication Required' },
};

export interface IHttpStatusInfo {
    code: number;
    response: string;
}
